apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service-deployment
  labels:
    app: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
      - name: delivery-service
        image: arsenteroganisyan/delivery-service:v8

        ports:
        - containerPort: 8000
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: port
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: host
          - name: USER
            valueFrom:
              secretKeyRef:
                name: secret
                key: user
          - name: DB
            valueFrom:
              configMapKeyRef:
                name: config
                key: db
          - name: PASSWRORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: password